prob_words_not_to_skip = ['PAINT', 'DUST', 'SCR', 'MOLDING', 'FUNCTION', 'INJECTION', 'DM', '불량', 'HIGH EFFORT',
                          'COUPLING', 'MECHANISM', 'NOISE', 'PACKING', 'EXTRA', 'POSITION', 'WELD', 'PRESS', 'RUST',
                          'HOLE', 'PIN', 'NUT', 'LEVEL', 'LEATHER', 'STICKER', 'ID', 'WELDING', 'OPEN', 'FLUSH',
                          'CHARGING']

prob_additional_exceptions = ['AA', 'AB', 'ACCORDING', 'ACID', 'ACTR', 'ACU', 'ACUTATOR', 'AFTER', 'XCIENT', 'KD',
                              'EHJ',
                              'ALSO', 'AN', 'ANTEENA', 'ANY', 'APPLICATION', 'AQL', 'ARE', 'AREA', 'ASAN', 'ASHA',
                              'ASSI',
                              'ASSY', 'AUTOGLASS', 'AUTOMOTIVE', 'AVAILABLE', 'BBD', 'BC', 'BDC', 'BDM', 'BE', 'BEFORE',
                              'BELT', 'BETWEEM', 'BETWEEN', 'BH', 'BJA', 'BJB', 'BJC', 'BMU', 'BOOSTER', 'BOTTOM', 'BQ',
                              'BRCT', 'BRD', 'BRK', 'BSA', 'BUTTONS', 'CA', 'CAME', 'CBR', 'CDC', 'CF', 'CHANG', 'QZC',
                              'CHEMICAL', 'CHNL', 'CHROME', 'CKLIP', 'CLEARLH', 'CLIPEND', 'CLOSING', 'CN', 'CNS', 'CO',
                              'COMBILAMP', 'COMES', 'COMING', 'COMPL', 'COMPLETE', 'CONCERN', 'CONNECTORS',
                              'CORPORATION', 'CRETA', 'CV', 'D&R', 'DAEDONG', 'DENSO', 'DH', 'DISCK', 'DKE', 'DL',
                              'DONG', 'DRRH', 'DUA', 'DUE', 'DURIGN', 'DURING', 'DY', 'ECOPLASTIC', 'ECOS', 'EK',
                              'ELEMENT', 'ENDPIECE', 'FB', 'FC', 'FE', 'FI', 'FOUND', 'FPSC', 'FR', 'FROM', 'FRT',
                              'FULLER', 'GCB', 'GCC', 'GCD', 'GCE', 'GCF', 'GE', 'GEARS', 'GI', 'GI', 'GIVING', 'GONG',
                              'GRL', 'GRUME', 'GSK', 'GSR', 'GX', 'HADS', 'HANKOOK', 'HAUSYS', 'HC', 'HCD', 'HCE',
                              'HCF',
                              'HCG', 'HCR', 'HDLLH', 'HE', 'HEADLAMP', 'HEADLH', 'HEADRH', 'HEE', 'HEMMING', 'HENKEL',
                              'HEUNG', 'HI', 'HING', 'HM', 'HMI', 'HMMC', 'HMSK', 'HOME', 'HTK', 'HX', 'HYUNDAI', 'IL',
                              'ILLUMINATION', 'IMT', 'INCOMING', 'IND', 'INDIA', 'INFAC', 'INFORMATION',
                              'INITIAL', 'INSPECTOR', 'INTERMOBILE', 'INTERNAL', 'IQR', 'IS', 'ISIR', 'ISSUE', 'ISSUES',
                              'IT', 'ITS', 'JIG', 'JIN', 'JNT', 'JOIL', 'JS', 'JULY', 'JUNG', 'JUST', 'KA', 'KAC', 'KF',
                              'KIA', 'KIMCHEON', 'KMS', 'KNIFE', 'KNOBB', 'KOMOS', 'KOREA', 'KWANGJIN', 'KYUNG', 'LANE',
                              'LEFT', 'LG', 'LH', 'LHD', 'LINKAGE', 'LIQUID', 'LN', 'LOADING', 'LOT', 'LOUD', 'LPL',
                              'LS', 'LTD', 'LUG', 'MANDO', 'MDPS', 'METAL', 'MJ', 'MOBIS', 'MODEL', 'MONETARY', 'MTGRH',
                              'MU', 'MULTIPLE', 'NAIL', 'NAJEON', 'NATIONAL', 'NEW', 'NG', 'NO.', 'NOIDA', 'NOTCH',
                              'NVH',
                              'OB', 'OBSERVED', 'OCCURRED', 'OF', 'OFFSET', 'OK', 'OPERATING', 'OPERATOR',
                              'PACKED', 'PADDLE', 'PBBLE', 'PCB', 'PCD', 'PCM', 'PDI', 'PHEV', 'PLAKOR', 'PLATECH',
                              'POONGSUNG', 'PP', 'PPR', 'PRESENTED', 'PRIVATE', 'PROTECTION', 'PRTN', 'PSTN',
                              'PTRH', 'PVT', 'PYUNG', 'QARTER', 'QB', 'QC', 'QRT', 'QUALITY', 'QXI', 'RATTLE', 'REAR',
                              'REFER', 'REISSUE', 'RELATED', 'REPAIR', 'OI', '로', 'QI', 'FOR', 'NTF', 'SIG', '돌때', '매우',
                              'REWORK', 'RH', 'RIB', 'ROCS', 'ROOFLH', 'RP', 'RR', 'RRDR', 'RRRH', 'RT', 'QF', 'ACA',
                              'RU', 'SAE', 'SAEDONG', 'SAMBOA', 'SAMBOPLATEC', 'SAME', 'SAMPLE', 'SAMSHIN', 'SAMSONG',
                              'SAN', 'SB', 'SC', 'SEAR', 'SEATBELT', 'SEATING', 'SECOND', 'SEEM', 'SENDER', 'SEOYON',
                              'SEQUENCING', 'SEUN', 'SHIN', 'SHINKI', 'SHLD', 'SHOWING', 'SIDELH', 'SL',
                              'SLH', 'SORTED', 'SOS', 'SPOOL', 'SQUEAK', 'SRH', 'SSUNGLASS', 'STAGE', 'STD', 'STICK',
                              'STUDBOLT', 'SUBCONTRACT', 'SUNG', 'SUNGLASS', 'SUNGLASSED', 'SUNGLASSES',
                              'SUPPLIER', 'SUV', 'SVG', 'TACHOMETER', 'TAE', 'TCU', 'TECH', 'TENSR', 'TF',
                              'THAN', 'THE', 'THERE', 'THORTTLE', 'TL', 'TLI', 'TMA', 'KWANGIL', 'INNOVATION', 'UMA',
                              'TOO', 'TR', 'TRANIT', 'TRANS', 'TRANSYS', 'TRG', 'TRIGO', 'TRW', 'TTX', 'TURNS', 'UI',
                              'UIP', 'UNIV', 'UNUSED', 'USED', 'VER', 'VIBRACOUSTIC', 'VISIBLE', 'VISUAL', 'VS', 'WAS',
                              'WEBASTO', 'WHEN', 'WHILE', 'WHISTLE', 'WI', 'WIA', 'WILL', 'WIRRING', 'WON', 'WOO',
                              'YOUNGSAN', 'YPI', 'YZ', 'КК''나전', '도어벨트', '만도', '스트라이커외', '오송', '으로', '인한',
                              'COMPRESSION', 'MTNG', 'BORE', 'VR', 'HOT', 'STAPLE', 'BULB', 'SEJIN', 'DELTARH', 'DRLH',
                              'JO', 'KMI', 'ACN', 'SAMBO', 'ILJIN', 'HLLD', 'JOYSON', 'SYSTEMS', 'YP', 'REPORT', 'QL',
                              'GAT', 'HCC', 'POLYURETHANE', 'CHE', 'JF', 'КК', 'WERE', 'REJECTED', 'FIT', 'LK', 'TOTE',
                              'NIL', '방안협의', 'ROFO', 'FRLH', 'GLA', 'CHB', 'OTRRH', 'LIFTGATE', 'BTZ', 'INVESTIGATION',
                              '업체사전신고', '클린포인트', 'VP', 'SX', 'DF', 'RB', 'PN', 'DN', 'PS', 'FM', 'AM', 'GR', 'NA',
                              'SA', 'MT', 'OR', 'VN', 'CH', 'OD', 'EL', 'PL', 'HO', 'MV', 'DP', 'TC', 'YU', 'LX', '조치',
                              'EO', 'DM', 'YB', 'SQ', 'ID', 'PA', 'BB', 'AHV', 'ANC', 'ASM', 'ASS', 'AWK', 'BAK', 'MQ',
                              'BCB', 'BCC', 'BIG', 'BPP', 'BRE', 'BRF', 'BUT', 'CHA', 'CHC', 'CHD', 'CHK', 'CRB', 'CRK',
                              'DEC', 'DIM', 'DLC', 'DTC', 'ESA', 'ESC', 'ETR', 'EVA', 'EXA', 'FEW', 'FGG', 'GAH', 'GRU',
                              'HAD', 'HCB', 'IGN', 'INA', 'INB', 'ITW', 'KPS', 'KUM', 'LIQ', 'MIS', 'MIX', 'MRG', 'MUA',
                              'NCM', 'ODO', 'OLL', 'ONE', 'OPN', 'PCS', 'PEW', 'PHO', 'PIN', 'VPC',
                              'RED', 'RIO', 'ROM', 'SDE', 'SHF', 'SUC', 'TPO', 'UQA', 'VIN', 'WCA', 'YDM', 'ASSR',
                              'ASST',
                              'BEEN', 'BOTH', 'BUMP', 'CASS', 'CIMB', 'CTPA', 'DOME', 'TLID', 'DTCP', 'EMBO', 'FIAL',
                              'HAVE',
                              'INFO', 'JBOX', 'KDQR', 'KMMG', 'LOT성', 'MUCH', 'NCAP', 'NICK', 'RRLH', 'THIS', 'TITL',
                              'WEBB',
                              'WHLD', 'WORK', 'WRMG', '弧度不良', '焊点分离', 'SEUNG', 'GUMMCHANG', 'SEWON', 'FOOSUNG', '인판넬',
                              '써모스탯', '오일필터', 'APRN', 'BRER', 'CEED', 'CHAN', 'CONV', 'COOL', 'EGIR', 'EGMP', 'EXTG',
                              'FCAR', 'FILR', 'FOIL', 'FOLD', 'FULE', 'GRAY', 'HTCV', 'IPDN', 'LATE', 'RSVR', 'SBMP',
                              'SELT',
                              'STAB', 'STAT', 'LH혼입', 'LING', 'MLDH', 'M미승인', 'OPRS', 'QSSY', 'QTMP', 'QZMP', 'REFL',
                              'TACK', 'TAKE', 'TEST', 'TION', 'ZEDO', '上海宝隆', '不良通报', '产品划伤', '产品受潮', '产品变形', '产品异种',
                              '产品污染',
                              '产品油斑', '产品生锈', '产品碰伤', '产品锈斑', '入库不良', '入库变形', '划伤不良', '前后混装', '包装不良', '包装变形', '包装淋湿',
                              '包装破损',
                              '北京万都', '北京世东', '北京大圆', '北京大有', '卡扣不良', '外观不良', '天津平和', '天津立中', '天津锦湖', '容易撕裂', '山东真元',
                              '工程不良',
                              '异种不良', '打磨变形', '托盘变形', '托盘破损', '护角移位', '数量不足', '数量异种', '月捷喜爱', '每日不良', '气泡不良', '江苏大起',
                              '涂装不良',
                              '涂装修补', '红点点反', '缺失配件', '色线不良', '色线磨损', '表面损伤', '表面破损', '轮毂压痕', '轮胎破损', '轮辋开裂', '部件生锈',
                              '部品异种',
                              '部品碰伤', '钢印不良', '铸造不良', '青岛东亚', '青岛东和', '风孔不良', '风孔焊渣', '龙口星宇', 'AI', 'A면',
                              'B골', 'CS', 'DW', 'EA', 'ED', 'EG', 'FD', 'GA', 'GD', 'HD', 'HF', 'HL', 'HT', 'HV', 'IB',
                              'IP',
                              'IR', 'JC', 'JD', 'KM', 'LD', 'LF', 'LM', 'LT', 'MP', 'NP', 'NX', 'N단', 'PD', 'PH', 'PO',
                              'PQ',
                              'PY', 'QM', 'QS', 'QT', 'QY', 'QZ', 'RD', 'RK', 'SF', 'TP', 'TQ', 'TU', 'TW', 'UD', 'UN',
                              'VM',
                              'VT', 'VU', 'VW', 'WK', 'XM', 'XN', 'YD', 'YF', 'YG', 'YN', 'YS', '不良', '东和', '凹坑', '划伤',
                              '压痕',
                              '变形', '廊坊', '异物', '打磨', '星宇', '月H', '月M', '毛刺', '气泡', '污染', '污渍', '油污', '涂装', '混品', '漏气',
                              '真元',
                              '破损', '磕伤', '磕碰', '磨损', '立中', '缺损', '脚印', '铸造', '颠倒', '龙口', 'ADD', 'ALC', 'APR',
                              'BAL', 'BLK', 'CSC', 'C엔진', 'DEL', 'DKD', 'DWI', 'EXP', 'FF용', 'HAM', 'HLA', 'HLW', 'INJ',
                              'IPE', 'JCA', 'JIT', 'KOP', 'KRN', 'LHV', 'LSU' 'NYC', 'NYV', 'OCT', 'OPR', 'OPT', 'PDE',
                              'PGU', 'PIT', 'QLE', 'QTC', 'QZE', 'RHD', 'ROF', 'RRC', 'R혼입', 'SEA', 'SIA', 'SIL', 'SLE',
                              'SOP', 'SWG', 'TON', 'TRK', 'UND', 'UPP', 'URG', 'VLV', 'WHE', 'WTS', '含铸造', '捷喜爱', '未成型',
                              '耐克森', '龙口M', '국내용', '김동현', '김현우', '김현일', '김홍장', '부근에', '유창근', '이동수', '이상윤',
                              '이승환', '장형규', '입고검사', '자주검사', '합동검사', 'ADD', '전수', '전수검사', '우승식', "LH", "RH"]
