import os

BASE_PYTHON = r"C:\Users\glovis-laptop\AppData\Local\Programs\Python\Python37"
VENV_64_DIR = os.path.join(os.getcwd(), 'venv')
SCRIPTS_DIR = os.path.join(VENV_64_DIR, 'Scripts')

REPOSITORY = r'https://github.com/asahi8769/partmaster.git'

PART_SYS_1 = {'0': 'SPACIAL PARTS', '1': 'STANDARD PARTS', '2': 'ENGINE', '3': 'ENGINE',
              '4': 'POWER TRAIN & CHASSIS-ETC', '5': 'POWER TRAIN & CHASSIS-ETC', '6': 'BODY', '7': 'BODY',
              '8': 'TRIM', '9': 'ELECTRICAL'}

PACKAGING_CENTER = {'GA': '아산1포장장', 'GB': '아산2포장장', 'GC': '아산3포장장', 'JB': '전주뷰텍', 'KG': '광주GLS(첨단)',
                    'KL': '광주GLS(평동)', 'KY': '광주YSP', 'U1': '울산1포장장', 'U2': '울산2포장장', 'YH': '울산하나TPS',
                    'YP': '울산PLS', 'YW': '울산유니팩'}

APPEARANCE_DICT = {
    "스크래치": [
        "스크래치",
        "스크레치",
        "스크래",
        "스크레",
        "긁힘",
        "굵힘",
        "쓸림",
        "긁",
        "Scratch",
        "SCRATCH",
        "SCRACHE",
        "SURFACE",
    ],
    "찢어짐": [
        "찢어짐",
        "찢김",
        "뜯김",
        "뜯어짐",
        "갈라짐",
        "짲어짐",
    ],
    "파손": [
        "파손",
        "손상",
        "깨짐",
        "꺠짐",
        "터짐",
        "크랙",
        "덴트",
        "DENT",
        "찍힘",
        "파단",
        "싱크",
        "씽크",
        "찍",
        "깨",
        "훼손",
        "破损",
        "손",
        "찢어",
        "꺽임",
        "꺾임",
        "CHOPPING",
        "잘림",
        "단선",
        "DAMAGE",
        "BROKEN",
        "CRACK",
        "DAMAN",
        "CRATER",
        "TORN"
    ],
    "변형": [
        "변형",
        "구부러짐",
        "눌림",
        "접힘",
        "찌그러짐",
        "휨",
        "넥",
        "네크",
        "휘어짐",
        "휘여짐",
        "벌어짐",
        "늘어짐",
        "늘어남",
        "수축",
        "이탈",
        "주름",
        "굴곡",
        "벗겨짐",
        "변",
        "들뜸",
        "밀림",
        "돌출",
        "DEFORM",
        "EXFOLIATION",
        "HOLE ON PART",
        "DEPRESSION",
        "BENT",
        "WAVY",
    ],
    "버": [
        "버",
        "BURR",
        "Burr",
        "BUrr",
        "burr",
    ],
    "오염": [
        "오염",
        "먼지",
        "분진",
        "수분유입",
        "수분 유입",
        "물유입",
        "물 유입",
        "젖음",
        "빗물",
        "유입",
        "자국",
        "탄화",
        "얼룩",
        "흐름",
        "굳음",
        "송홧가루",
        "뭉침",
        "오",
        "플로킹",
        "스코치",
        "누수",
        "본딩",
        "눈쌓임",
        "DIRTY",
        "STAIN",
        "성에",
        "유분",
        "누유",
        "PAINT",
        "SEALANT",
        "STICKY",
        "GRUMES",
        "DRIP",
        "POLLUTION",
        "CONTAMINATION",
        "CHIP",
        "칩",
        "DIRT",
        'MARK',
        "DUST",
        "CHIPPED",
        "DROP",
    ],
    "발청": [
        "발청",
        "부식",
        "백화",
        "녹",
        "발",
        "RUST",
        "CORROSION",
    ],
    "사상불량": [
        "사상불량",
        "사상 불량",
        "미사상",
        "과사상",
        "사상",
        "SANDING",
    ],
    "도금불량": [
        "도금불량",
        "미도금",
        "도금 불량",
        "도금뭉침",
        "도금",
        "도금 박리",
        "도금박리",
    ],
    "이색": [
        "이색",
        "변색",
        "컬러",
        "BRIGHT SPOTS",
        "COLOR",
    ],
    "도장불량": [
        "도장불량",
        "도장벗겨짐",
        "도장 벗겨짐",
        "미도장",
        "도장 칠흐름",
        "칠흐름",
        "도장박리",
        "도장 박리",
        "도장",
        "이물질",
        "이물",
        "칠",
        "FOREIGN",
        "SEED",
        "VARNISH",
    ],
    "타각불량": [
        "타각불량",
        "타각 불량",
        "타각",
    ],
    "성형불량": [
        "성형불량",
        "성형 불량",
        "미성형",
        "성형",
        "덧살",
    ],
    "사출불량": [
        "사출",
        "MOLD DEFECT",
        "가스",
        "기포",
        "BUBBLE",
        "MOLDING PROBLEM",
        "JOINT PROBLEM",
        "INJECTION",
        "BLOW HOLES",
        "POROSITY",
        "MOLDING",
        "BOILING",
        "WHITE SPOTS",
    ],
    "봉제불량": [
        "봉제불량",
        "식모불량",
        "식모",
        "스티치",
        "실밥",
        "웨빙",
    ],
    "홀가공불량": [
        "홀가공불량",
        "홀 누락",
        "홀누락",
        "홀 막힘",
        "홀막힘",
        "홀",
        "MISSING HOLE",
        "PUNCHINIG",
    ],
    "용접불량": [
        "용접불량",
        "용접 불량",
        "용접칩",
        "용접",
        "용접액",
        "웰드라인",
        "WELDING",
    ],
    "포장": [
        "포장불량",
        "포장",
    ],
    "방청유문제": [
        "방청유",
        "미도포",
        '구리스',
    ],
    "접착불량": [
        "접착불량",
        "접착 불량",
        "접합불량",
        "접합 불량",
        "접착불",
        "ADHESIVE",
    ],
    "서브품불량": [
        "서브품 누락",
        "서브품누락",
        "서브품 불량",
        "서브품불량",
        "SUB",
        "sub",
        "서브품",
        "MISSING",
        "MISSED",
        "MISSIN",
    ],
    "재단불량": [
        "재단불량",
        "커팅불량",
        "컷팅불량",
        "CUT"
    ],
    "주물불량": [
        "형상불량",
        "프레스",
    ],
    "공정누락": [
        "공정누락",
        "공정 누락",
        "누락",
        "미제거",
        "MISSING HOLE",
    ],

    "이종": [
        "식별표",
        "혼입",
        "이종",
        "식별라벨",
        "구형",
        "사양",
        "라벨",
        "타차종",
        "라벨",
        "식별",
        "WRONG PART",
        "MIXED",
        "DIFFERENT TYPE",
        "WRONG FORM",
        "WRONG SHAPE",
        "WRONG DIMENSION",
        "혼적",
    ],
    "수량과부족": [
        "수량",
        "과납",
        "부족",
    ],
    "가공불량": [
        "코팅",
        "유광",
        "광택",
        "작업불량",
        "가공불량",
        "가공 불량",
        "가공불량",
        "가공 미흡",
        "가공",
        "떨어짐",
        "가공 누락",
        "가공누락",
        "가공 미흡",
        "기공",
        "작업불",
        "패드",
        "마감",
        "박리",
        "소재결육",
        "슬러지",
        "풀림",
        "가공누",
        "MACHINING",
        "SPATTER",
        "DETACH",
        "SOLDERING",
        "SEPARATION",

    ],
    "조립불량": [
        "단차",
        "과조립",
        "갭",
        "역조립",
        "조립",
        "덜조임",
        "틈새",
        "ASSEMBLY",
        "POSITION",
        "미체결",
        "미조립",
        "LOOSE",
        "GAP",
    ],
    "기타외관불량": [
        "흑점",
        "인쇄불량",
        "인쇄",
        "외관불량",
        "외관 불량",
        "통보",
        "입고",
        "부품문제",
        "불량",
        "결함",
    ],

}

SQL_SCHEMA = {
    "파트마스터": """CREATE TABLE "파트마스터" (
	"번호"	INTEGER NOT NULL UNIQUE,
	"고객사"	TEXT,
	"차종"	TEXT,
	"Part No"	TEXT,
	"부품명"	TEXT,
	"단위"	TEXT,
	"SRC"	TEXT,
	"Type"	TEXT,
	"부품그룹"	TEXT,
	"게이트"	TEXT,
	"포장장"	TEXT,
	"사업장"	TEXT,
	"통화"	TEXT,
	"납품업체"	TEXT,
	"납품업체명"	TEXT,
	"카덱스"	TEXT,
	"운송업체"	TEXT,
	"운송업체.1"	TEXT,
	"선행일수"	TEXT,
	"케이스적입수"	TEXT,
	"최대발주량"	TEXT,
	"USAGE"	TEXT,
	"업체 Capa"	TEXT,
	"용기코드"	TEXT,
	"용기수납수"	TEXT,
	"용기수_대차당편성"	TEXT,
	"용기수_상수"	TEXT,
	"Loc."	TEXT,
	"C.C"	TEXT,
	"라인"	TEXT,
	"중박스"	TEXT,
	"이재박스"	TEXT,
	"티켓출력"	TEXT,
	"좌우구분"	TEXT,
	"참고_1"	TEXT,
	"참고_2"	TEXT,
	"참고_3"	TEXT,
	"참고_4"	TEXT,
	"꼬리표 미적용"	TEXT,
	"중박스.1"	TEXT,
	"대박스"	TEXT,
	"사급상위부품여부"	TEXT,
	"사급여부"	TEXT,
	"검사"	TEXT,
	"MIP 부품"	TEXT,
	"ENG TM"	TEXT,
	"납입시각_1"	TEXT,
	"납입시각_2"	TEXT,
	"납입시각_3"	TEXT,
	"납입시각_4"	TEXT,
	"납입시각_5"	TEXT,
	"납입시각_6"	TEXT,
	"납입시각_7"	TEXT,
	"납입시각_8"	TEXT,
	"입고소요시간 (분)"	TEXT,
	"사용중지"	TEXT,
	"생성일자"	TEXT,
	"등록자"	TEXT,
	"최종수정일시"	TEXT,
	"최종수정자"	TEXT,
	"원산지국가코드"	TEXT,
	"포장대행여부"	TEXT,
	"대표품번"	TEXT,
	"부품종류"	TEXT,
	"납입예정 해제_적용여부"	TEXT,
	"납입예정 해제_유효일자"	TEXT,
	"납입예정 해제_적용여부.1"	TEXT,
	"납입예정 해제_유효일자.1"	TEXT,
	"납입예정 해제_적용여부.2"	TEXT,
	"납입예정 해제_유효일자.2"	TEXT,
	"부품로트 대상여부"	TEXT,
	PRIMARY KEY("고객사","차종","Part No")
);""",
    "중점검사표": """CREATE TABLE "중점검사표" (
	"No"	INTEGER NOT NULL UNIQUE,
	"중점검사표"	TEXT,
	"고객사"	TEXT,
	"차종"	TEXT,
	"업체코드"	TEXT,
	"업체명"	TEXT,
	"Part No"	TEXT,
	"부품명"	TEXT,
	"등록일자"	INTEGER,
	"부품구분"	TEXT,
	"안전/보안"	TEXT,
	PRIMARY KEY("고객사","차종","업체코드","Part No","중점검사표")
);""",
    "입고불량이력": """CREATE TABLE "입고불량이력" (
	"No"	INTEGER NOT NULL UNIQUE,
	"통보서번호"	TEXT,
	"상태상세"	TEXT,
	"고객사"	TEXT,
	"차종"	TEXT,
	"코드"	TEXT,
	"업체명"	TEXT,
	"Part No"	TEXT,
	"부품명"	TEXT,
	"검사일자"	TEXT,
	"등록일자"	TEXT,
	"발생일자"	TEXT,
	"결재1소요일"	TEXT,
	"결재2소요일"	TEXT,
	"결재3소요일"	TEXT,
	"통보일자"	TEXT,
	"입고불량 처리소요일"	TEXT,
	"대책요구일자"	TEXT,
	"대책확인일자"	TEXT,
	"대분류명"	TEXT,
	"중분류명"	TEXT,
	"소분류명"	TEXT,
	"2차 업체명"	TEXT,
	"불량수량"	TEXT,
	"검사자"	TEXT,
	"현황"	TEXT,
	"대분류명.1"	TEXT,
	"중분류명.1"	TEXT,
	"소분류명.1"	TEXT,
	"불량구분"	TEXT,
	"불량조치"	TEXT,
	"사업장"	TEXT,
	"포장장"	TEXT,
	"게이트"	TEXT,
	"검사번호"	TEXT,
	"제목"	TEXT,
	"LOT No"	TEXT,
	"불량발견장소"	TEXT,
	PRIMARY KEY("고객사","차종","코드","업체명","Part No","통보서번호")
);""",
    "해외불량이력": """CREATE TABLE "해외불량이력" (
	"No"	INTEGER NOT NULL UNIQUE,
	"진행상태"	TEXT,
	"결재상태"	NUMERIC,
	"KDQR Type"	TEXT,
	"대표PPR No"	TEXT,
	"PPR No"	TEXT,
	"KDQR No"	TEXT,
	"담당자"	TEXT,
	"공급법인"	TEXT,
	"고객사"	TEXT,
	"차종"	TEXT,
	"코드"	NUMERIC,
	"부품협력사"	TEXT,
	"품번"	TEXT,
	"품명"	TEXT,
	"귀책구분"	TEXT,
	"코드.1"	TEXT,
	"귀책처"	TEXT,
	"발생처"	TEXT,
	"불량수량"	INTEGER,
	"조치수량"	INTEGER,
	"Monetary"	TEXT,
	"Replacement"	TEXT,
	"Exchange"	TEXT,
	"Repair"	TEXT,
	"클레임수량"	TEXT,
	"불량구분"	TEXT,
	"불량유형(대)"	TEXT,
	"불량유형(중)"	TEXT,
	"불량유형(소)"	TEXT,
	"제목"	TEXT,
	"발생일자"	TEXT,
	"등록일자"	TEXT,
	"해외결재일"	TEXT,
	"국내접수일"	TEXT,
	"국내결재일"	TEXT,
	"공급국가"	TEXT,
	"Type"	TEXT,
	"공장"	TEXT,
	"중요도"	TEXT,
	"긴급도"	TEXT,
	"System"	TEXT,
	"Shop"	TEXT,
	"CC"	TEXT,
	"Shipmode"	TEXT,
	"P/T Model"	TEXT,
	"대책작성여부"	TEXT,
	"오더번호"	TEXT,
	"대책등록일"	TEXT,
	"대책확인일"	TEXT,
	"대책확인일(해외)"	TEXT,
	"개선일"	TEXT,
	"개선적용오더"	TEXT,
	"발생원인(대)"	TEXT,
	"발생원인(중)"	TEXT,
	"발생원인(소)"	TEXT,
	"최종조립처"	TEXT,
	"유니크여부"	TEXT,
	"2차사여부"	TEXT,
	"2차사명"	TEXT,
	"현재결재자"	TEXT,
	PRIMARY KEY("KDQR Type","대표PPR No","PPR No","KDQR No","고객사","차종","코드","품번")
);""",
    "전차종포장사양서": """CREATE TABLE "전차종포장사양서" (
	"고객사차종"	TEXT,
	"고객사"	TEXT,
	"차종코드"	TEXT,
	"부품코드"	TEXT,
	"부품명"	TEXT,
	"최종입고일자"	TEXT,
	"적용시작일자"	TEXT,
	"포장장"	TEXT,
	"중박스코드"	TEXT,
	"중박스수용수"	TEXT,
	"대박스코드"	TEXT,
	"대박스수용수"	TEXT,
	"단중"	TEXT,
	"총중량"	TEXT,
	"총중량M"	TEXT,
	"총중량C"	TEXT,
	"업체포장유상사용"	TEXT,
	"업체포장무상사용"	TEXT,
	"업체박스가로치수"	TEXT,
	"업체박스세로치수"	TEXT,
	"업체박스높이치수"	TEXT,
	"이재수수용수"	TEXT,
	"묶음개수수용수"	TEXT,
	"포장방법"	TEXT,
	"부품특징"	TEXT,
	"주의사항"	TEXT,
	"부품업체중포장여부"	TEXT,
	"부품업체대포장여부"	TEXT,
	"방청"	TEXT,
	"양산"	TEXT,
	"무상"	TEXT,
	"사용여부"	TEXT,
	"EPType"	TEXT,
	"포장순서도"	TEXT,
	"과거포장품질"	TEXT,
	"부품업체"	TEXT,
	"부품업체명"	TEXT,
	"단품사진"	TEXT,
	"중포장사진"	TEXT,
	"주의사항사진"	TEXT,
	"동일품번기준사양"	TEXT,
	"기준사양불일치"	TEXT,
	"기준사양불일치파일명"	TEXT,
	"대박스표준준수"	TEXT,
	"대박스표준준수파일명"	TEXT,
	"상세내용"	TEXT,
	"혼입"	TEXT,
	"직출하여부"	TEXT,
	PRIMARY KEY("고객사","차종코드","부품코드")
);""",
    "품번체계": """CREATE TABLE "품번체계" (
	"품번"	TEXT,
	"부품구분"	TEXT,
	PRIMARY KEY("품번")
);"""
}
